function newENU = rotationXYZExtrinsic(ENUpos, rotX,rotY,rotZ)
    rotMat = [ ...
        cos(rotZ)*cos(rotY),  cos(rotZ)*sin(rotY)*sin(rotX) - sin(rotZ)*cos(rotX),  cos(rotZ)*sin(rotY)*cos(rotX) + sin(rotZ)*sin(rotX); ...
        sin(rotZ)*cos(rotY),  sin(rotZ)*sin(rotY)*sin(rotX) + cos(rotZ)*cos(rotX),  sin(rotZ)*sin(rotY)*cos(rotX) - cos(rotZ)*sin(rotX); ...
        -sin(rotY),           cos(rotY)*sin(rotX),                                  cos(rotY)*cos(rotX) ...
    ];
    newENU = rotMat * ENUpos;
end